### ISSUE TITLE
Implement auto save functionality for tutorial builder

### ISSUE THREAD

**Issue by JetJet13** [mathbookio/mathbook#17]
Feature Request
===
I would like the tutorial builder to auto save my progress and state on my behalf so that when there is an accidental exit, or my sessions expires when I'm trying to save the state myself or if my computer randomly shuts down,  my unsaved changes aren't lost.

For example, It could auto save every x amount of seconds or on `loseFocus` events.

**Comment by mathbook-io** [comment]
👍
