### ISSUE TITLE
Create a Style Guide

### ISSUE THREAD

**Issue by jgeorges371** [mathbookio/mathbook#73]
There needs to be some kind of style guide for when we want to declare a definition or highlight an important part of the content of a tutorial. 

There also needs to be a centralized place where contributors can go and look up and reference the style guide. 

Kudos goes to @rich1126 for bringing this up.

**Comment by JetJet13** [comment]
Here's the first iteration of the style guide. 

https://github.com/JetJet13/mathbook/wiki/Tutorial-Style-Guide
