### ISSUE TITLE
Navbar dropdown bug

### ISSUE THREAD

**Issue by Gh0stByte** [mathbookio/mathbook#83]
Bug in navbar dropdowns
===
### Description
The dropdown menus are not working as expected

### How to Reproduce
1. Login
2. Click the ```Contribute``` dropdown
3. Click the ```Logged in as NAME``` dropdown
4. Both remain open
5. Click away, outside of the dropdowns
6. They remain open

### Actual Behavior
Clicking away from the dropdowns does not close them, and both can be selected at the same time causing overlap

### Expected Behavior
When clicking away, the dropdowns close, and only one can be opened at a time

### Additional Info
OS: Windows 10,
Browser: Firefox Developer

### Current Workaround
None

**Comment by JetJet13** [comment]
That's a nice find! 

I'll try and prioritize this over the coming weeks however feel free to pick this up if you want :)

As a side note. Thanks for following the [Bug Reporting Guidelines](https://github.com/JetJet13/mathbook/wiki/Bug-Reporting-Guideline).

**Comment by JetJet13** [comment]
A fix has been implemented and merged to develop. #100
