### ISSUE TITLE
Transfer ownership of repo to mathbook-io user

### ISSUE THREAD

**Issue by mathbook-io** [mathbookio/mathbook#87]
In order to keep my own personal account JetJet13 from being the main source of this repository, I created this account `mathbook-io` so I can transfer the ownership of mathbook to this account. 

This gives us the benefit of having the repo clean of any development branches that I may be working on. I also don't want this project to look like I'm the owner because I believe that this project belongs to those who contribute towards it.

I will need to get things setup (i.e. Mathbook OAuth app) and make some small code changes on before I transfer this repo which I plan on doing in the near future.

**Comment by JetJet13** [comment]
This is now complete! No issues to report 👍
